name: CD Deploy to AWS

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Application
        env:
          SSH_PASSWORD: ${{ secrets.AWS_PASSWORD }}
          HOST_NAME: ${{ secrets.AWS_HOST }}
          USER_NAME: ${{ secrets.AWS_USERNAME }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USER_NAME@$HOST_NAME << 'EOF'
            cd ~/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
          EOF

